### ISSUE TITLE
dependency-track Azure OpenId configuration

### ISSUE THREAD

**Issue by iamrahul127** [evryfs/helm-charts#153]
Dear Team, Thank you for excellent work. Let me apologize using bug template but I don't see any template which can be used for asking question. 
I am trying to integrate dependency-track with Azuer OpenId and not sure how to do that as there is no single consolidated documentation available. I looked into multiple sources and got confused to be honest. Following is my finding and lots of questions may be :).

1. Default values.yaml 
    ```
      frontend:
      enabled: true
      replicaCount: 2
      image:
        repository: dependencytrack/frontend
        tag: 4.4.0
        pullPolicy: IfNotPresent    
        configmap:
        config: |
          {
              "API_BASE_URL": "",
              "OIDC_ISSUER": "",
              "OIDC_CLIENT_ID": "",
              "OIDC_SCOPE": "openid profile email",
              "OIDC_FLOW": ""
         }    
      env:
        - name: API_BASE_URL
          value: ""

2.  Is it possible to configure OpenId integration using config map shown above? Do we need to refer https://docs.dependencytrack.org/getting-started/configuration/.
3. Do we need to set API_BASE_URL? I am using nginx proxy so not providing any.
4. Then so get additional help, I googled and come across https://github.com/DependencyTrack/dependency-track/discussions/1104#discussioncomment-1003713.
    This has added more confusion as it has more environment variable for apiserver & frontend server. 
        
What I am looking for is concreate steps which enables me to configure the integration. I promise to update documentation with exact steps and create the PR for you. You can directly reach out to me in Tietoevry.

Regards
Rahul Mahulkar

**Comment by davidkarlsen** [comment]
Try this config:
```yaml
 frontend:
      replicaCount: 1
      env:
      - name: OIDC_ISSUER
        value: "https://login.microsoftonline.com/<TENANTID>/v2.0"
      - name: OIDC_CLIENT_ID
        value: <theClientId>
      - name: OIDC_SCOPE
        value: "openid profile email"
    apiserver:
      env:
      - name: ALPINE_OIDC_CLIENT_ID
        value: <theClientId>
      - name: ALPINE_OIDC_ENABLED
        value: "true"
      - name: ALPINE_OIDC_ISSUER
        value: "https://login.microsoftonline.com/<TENANTID>/v2.0"
      - name: ALPINE_OIDC_USERNAME_CLAIM
        value: email
      - name: ALPINE_OIDC_USER_PROVISIONING
        value: "true"
```
