### ISSUE TITLE
[dependency-track] Overriding ingress configuration via values.yaml

### ISSUE THREAD

**Issue by saintmalik** [evryfs/helm-charts#228]
**Describe the bug**
I was trying to override the spec.paths values of my ingress, but the chart predefined paths kept overriding them, so i had to manually edit the values of the ingress through OpenLens app

**Version of Helm and Kubernetes**:
1.25 and 3.10.0

**Which chart**:
dependency-track

**What happened**:
my defined ingress rules are getting overridden by the charts defined values

**What you expected to happen**:
i want to set the ingress paths myself like this

```
spec:
  rules:
    - host: example.com
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dependency-track-apiserver
                port:
                  number: 8085
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dependency-track-frontend
                port:
                  number: 8084
```

**How to reproduce it** (as minimally and precisely as possible):

use this values for your ingress

```
ingress:
  enabled: true
  tls:
    enabled: false
    secretName: ""
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: example.com
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dependency-track-apiserver
                port:
                  number: 8085
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dependency-track-frontend
                port:
                  number: 8084

```

**Anything else we need to know**:
