### ISSUE TITLE
[mcrouter] Wrong memcached service name in configmap

### ISSUE THREAD

**Issue by dragoangel** [evryfs/helm-charts#251]
**Describe the bug**
Proper naming should be:
```
{
  "pools": {
    "A": {
      "servers": [
        // hosts of replicated pool, https://github.com/facebook/mcrouter/wiki/Replicated-pools-setup e.g.:
        "mcrouter-memcached-0.mcrouter-memcached.mcrouter.svc.cluster.local:11211",
        "mcrouter-memcached-1.mcrouter-memcached.mcrouter.svc.cluster.local:11211",
        "mcrouter-memcached-2.mcrouter-memcached.mcrouter.svc.cluster.local:11211",
      ]
    }
  },
```
but by default service names generated as `mcrouter-0.mcrouter.mcrouter.svc.cluster.local:11211` resulting in non-working mcrouter, template missing `-memcached` twice, for pod and for service names.

**Version of Helm and Kubernetes**:
```
helm v3.12.3
kubernetes v1.24.15

**Which chart**:
mcrouter
```
**What happened**:
wrong configuration applied by default

**What you expected to happen**:
default config have proper settings to work

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

```yaml
dependencies:
  - name: memcached
    version: ~6.6
    repository: https://charts.bitnami.com/bitnami
    condition: mcrouter.memcached.enabled

```

condition `mcrouter.memcached.enabled` should be `memcached.enabled`?
