### ISSUE TITLE
Openshift deployment failed

### ISSUE THREAD

**Issue by carloreggiani** [evryfs/helm-charts#28]
Trying to deploy with helm on Openshift (4.5.16), error from deployment: 

FailedCreate
create Pod dependency-track-postgresql-0 in StatefulSet dependency-track-postgresql failed error: pods "dependency-track-postgresql-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000740000, 1000749999]]

Here the helm chart installed:
```
$ helm list
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
dependency-track        dependency-track        1               2020-11-05 11:12:47.0016078 +0100 CET   deployed        dependency-track-0.2.4  3.8.0
```

**Comment by davidkarlsen** [comment]
Ah - Openshift... You need to either:
a) oc adm policy add-scc-to-group anyuid <the serviceaccounts>
or 
b) change the uid to be in the allowed range.

**Comment by carloreggiani** [comment]
Thank you for replay David
 
> Ah - Openshift... You need to either:
> a) oc adm policy add-scc-to-group anyuid

Nope: from OpenShift 4.4 it is deprecated any global scc policy change

> or
> b) change the uid to be in the allowed range.

How? I have to rebuild the docker image?

Carlo

**Comment by davidkarlsen** [comment]
> Thank you for replay David
> 
> > Ah - Openshift... You need to either:
> > a) oc adm policy add-scc-to-group anyuid
> 
> Nope: from OpenShift 4.4 it is deprecated any global scc policy change
Interesting - do you have a link?

> 
> > or
> > b) change the uid to be in the allowed range.
> 
> How? I have to rebuild the docker image?
It uses the bitnami postgresql chart: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml - so any values there can be defined under the postgresl key, example: `postgresql.image.registry: myregistry/myimage`

**Comment by carloreggiani** [comment]
> > > Ah - Openshift... You need to either:
> > > a) oc adm policy add-scc-to-group anyuid
> > 
> > 
> > Nope: from OpenShift 4.4 it is deprecated any global scc policy change
> 
> Interesting - do you have a link?

From 4.3.8: no way to upgrade the cluster anymore with scc policy change, I run this issue :(
https://access.redhat.com/solutions/4972291

> 
> > > or
> > > b) change the uid to be in the allowed range.
> > 
> > 
> > How? I have to rebuild the docker image?
> 
> It uses the bitnami postgresql chart: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml - so any values there can be defined under the postgresl key, example: `postgresql.image.registry: myregistry/myimage`

Thank you, I'll try

Carlo

**Comment by davidkarlsen** [comment]
@carloreggiani 
Did you get it to work? Can we close the issue?

A cleaner way to provide access to scc's is through rolebindings:
```
k get rolebinding scc-anyuid -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scc-anyuid
  namespace: yournamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:yournamespace
```
