### ISSUE TITLE
Application properties not being used

### ISSUE THREAD

**Issue by andrew-sumner** [evryfs/helm-charts#36]
I've got exactly the same problem as issue #7, for some reason this was closed without an answer.

Any ideas?

In my case I'm trying to setup the database connection. So part 2 of this question is how do I include sqljdbc4.jar as documented here https://docs.dependencytrack.org/getting-started/database-support/

**Comment by davidkarlsen** [comment]
Have you set the values as in: https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L96 ? 
If you shell into the container, what does /config look like? There should be an `application.properties` with the values set in the step above.
This file is pointed to with the env-var:
```
set|grep /conf
ALPINE_APPLICATION_PROPERTIES='/config/application.properties'
```

**Comment by davidkarlsen** [comment]
Also note that drivers are already present in:
```
ls -l /extlib/
total 2732
-rw-r--r--    1 dtrack   dtrack      960558 Sep 29  2019 mssql-jdbc-7.1.3.jre8-preview.jar
-rw-r--r--    1 dtrack   dtrack     1007502 Sep 29  2019 mysql-connector-java-5.1.47.jar
-rw-r--r--    1 dtrack   dtrack      825943 Sep 29  2019 postgresql-42.2.5.jar
/extlib $ 
```

**Comment by andrew-sumner** [comment]
ALPINE_APPLICATION_PROPERTIES environment var does not exist, only one I found was ALPINE_DATA_DIRECTORY='/data'.

To install I've used:
helm repo add evryfs-oss https://evryfs.github.io/helm-charts/
helm upgrade dependency-track evryfs-oss/dependency-track -f values.yaml --install --namespace dev-tools

For values.yaml I had copied the contents of the file you linked to and updated as appropriate, eg:

**Values.yaml**

```
# Default values for dependency-track.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Max: 1 - DT is not designed for HA
replicaCount: 1

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 1500m
    memory: 4Gi
  limits:
    cpu: 4
    memory: 16Gi

nodeSelector: {}

tolerations: []

affinity: {}

env: 
- name: http_proxy
  value: http://INFNZ%5Csrv-dependecy-track:*****@ourproxy.co.nz:80
- name: https_proxy
  value: http://INFNZ%5Csrv-dependecy-track:*****@ourproxy.co.nz:80
- name: no_proxy
  value: .ourdomain.co.nz,.ourdomain.co.nz,localhost,127.0.0.1

service:
  type: LoadBalancer
  port: 8080

persistentVolume:
  enabled: true
  size: 8Gi
  annotations: {}
  storageClass: "vsphere-t5"

emptyDir:
  sizeLimit: 8Gi

configmap:
  application.properties: |
    ############################ Alpine Configuration ###########################
    # Required
    # Defines the number of worker threads that the event subsystem will consume.
    # Events occur asynchronously and are processed by the Event subsystem. This
    # value should be large enough to handle most production situations without
    # introducing much delay, yet small enough not to pose additional load on an
    # already resource-constrained server.
    # A value of 0 will instruct Alpine to allocate 1 thread per CPU core. This
    # can further be tweaked using the alpine.worker.thread.multiplier property.
    # Default value is 0.
    alpine.worker.threads=0

    # Required
    # Defines a multiplier that is used to calculate the number of threads used
    # by the event subsystem. This property is only used when alpine.worker.threads
    # is set to 0. A machine with 4 cores and a multiplier of 4, will use (at most)
    # 16 worker threads. Default value is 4.
    alpine.worker.thread.multiplier=4

    # Required
    # Defines the path to the data directory. This directory will hold logs, keys,
    # and any database or index files along with application-specific files or
    # directories.
    alpine.data.directory=~/.dependency-track

    # Required
    # Defines the interval (in seconds) to log general heath information. If value
    # equals 0, watchdog logging will be disabled.
    alpine.watchdog.logging.interval=0

    # Required
    # Defines the database mode of operation. Valid choices are:
    # 'server', 'embedded', and 'external'.
    # In server mode, the database will listen for connections from remote hosts.
    # In embedded mode, the system will be more secure and slightly faster.
    # External mode should be used when utilizing an external database server
    # (i.e. mysql, postgresql, etc).
    alpine.database.mode=external

    # Optional
    # Defines the TCP port to use when the database.mode is set to 'server'.
    # alpine.database.port=9092

    # Required
    # Specifies the JDBC URL to use when connecting to the database.
    alpine.database.url=jdbc:sqlserver://Lisnr_PD:50927;databaseName=DependencyTrack;
    
    # Required
    # Specifies the JDBC driver class to use.
    alpine.database.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

    # Optional
    # Specifies the path (including filename) to where the JDBC driver is located.
    alpine.database.driver.path=/extlib/mssql-jdbc-7.1.3.jre8-preview.jar

    # Optional
    # Specifies the username to use when authenticating to the database.
    alpine.database.username=dtrack

    # Optional
    # Specifies the password to use when authenticating to the database.
    alpine.database.password=*****

    # Optional
    # Specifies if the database connection pool is enabled.
    alpine.database.pool.enabled=true

    # Optional
    # This property controls the maximum size that the pool is allowed to reach,
    # including both idle and in-use connections.
    alpine.database.pool.max.size=10

    # Optional
    # This property controls the maximum amount of time that a connection is
    # allowed to sit idle in the pool.
    alpine.database.pool.idle.timeout=600000

    # Optional
    # This property controls the maximum lifetime of a connection in the pool.
    # An in-use connection will never be retired, only when it is closed will
    # it then be removed.
    alpine.database.pool.max.lifetime=600000

    # Optional
    # When authentication is enforced, API keys are required for automation, and
    # the user interface will prevent anonymous access by prompting for login
    # credentials.
    alpine.enforce.authentication=true

    # Optional
    # When authorization is enforced, team membership for both API keys and user
    # accounts are restricted to what the team itself has access to. To enforce
    # authorization, the enforce.authentication property (above) must be true.
    alpine.enforce.authorization=true

    # Required
    # Specifies the number of bcrypt rounds to use when hashing a users password.
    # The higher the number the more secure the password, at the expense of
    # hardware resources and additional time to generate the hash.
    alpine.bcrypt.rounds=14

    # Required
    # Defines if LDAP will be used for user authentication. If enabled,
    # alpine.ldap.* properties should be set accordingly.
    alpine.ldap.enabled=true

    # Optional
    # Specifies the LDAP server URL
    # Example (Microsoft Active Directory):
    #    alpine.ldap.server.url=ldap://ldap.example.com:3268
    #    alpine.ldap.server.url=ldaps://ldap.example.com:3269
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.server.url=ldap://ldap.example.com:389
    #    alpine.ldap.server.url=ldaps://ldap.example.com:636
    alpine.ldap.server.url=ldap://ldapserver.co.nz:389

    # Optional
    # Specifies the base DN that all queries should search from
    alpine.ldap.basedn=*****

    # Optional
    # Specifies the LDAP security authentication level to use. Its value is one of
    # the following strings: "none", "simple", "strong". If this property is empty
    # or unspecified, the behaviour is determined by the service provider.
    alpine.ldap.security.auth=simple

    # Optional
    # If anonymous access is not permitted, specify a username with limited access
    # to the directory, just enough to perform searches. This should be the fully
    # qualified DN of the user.
    alpine.ldap.bind.username=srv-dependecy-track@ourcompany.co.nz

    # Optional
    # If anonymous access is not permitted, specify a password for the username
    # used to bind.
    alpine.ldap.bind.password=*****

    # Optional
    # Specifies if the username entered during login needs to be formatted prior
    # to asserting credentials against the directory. For Active Directory, the
    # userPrincipal attribute typically ends with the domain, whereas the
    # samAccountName attribute and other directory server implementations do not.
    # The %s variable will be substitued with the username asserted during login.
    # Example (Microsoft Active Directory):
    #    alpine.ldap.auth.username.format=%s@example.com
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.auth.username.format=%s
    alpine.ldap.auth.username.format=%s@ourcompany.co.nz

    # Optional
    # Specifies the Attribute that identifies a users ID
    # Example (Microsoft Active Directory):
    #    alpine.ldap.attribute.name=userPrincipalName
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.attribute.name=uid
    alpine.ldap.attribute.name=userPrincipalName

    # Optional
    # Specifies the LDAP attribute used to store a users email address
    alpine.ldap.attribute.mail=mail

    # Optional
    # Specifies the LDAP search filter used to retrieve all groups from the
    # directory.
    # Example (Microsoft Active Directory):
    #    alpine.ldap.groups.filter=(&(objectClass=group)(objectCategory=Group))
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.groups.filter=(&(objectClass=groupOfUniqueNames))
    alpine.ldap.groups.filter=(&(objectClass=group)(objectCategory=Group))

    # Optional
    # Specifies the LDAP search filter to use to query a user and retrieve a list
    # of groups the user is a member of. The {USER_DN} variable will be substituted
    # with the actual value of the users DN at runtime.
    # Example (Microsoft Active Directory):
    #    alpine.ldap.user.groups.filter=(&(objectClass=group)(objectCategory=Group)(member={USER_DN}))
    # Example (Microsoft Active Directory - with nested group support):
    #    alpine.ldap.user.groups.filter=(member:1.2.840.113556.1.4.1941:={USER_DN})
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.user.groups.filter=(&(objectClass=groupOfUniqueNames)(uniqueMember={USER_DN}))
    alpine.ldap.user.groups.filter=(member:1.2.840.113556.1.4.1941:={USER_DN})

    # Optional
    # Specifies the LDAP search filter used to search for groups by their name.
    # The {SEARCH_TERM} variable will be substituted at runtime.
    # Example (Microsoft Active Directory):
    #    alpine.ldap.groups.search.filter=(&(objectClass=group)(objectCategory=Group)(cn=*{SEARCH_TERM}*))
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.groups.search.filter=(&(objectClass=groupOfUniqueNames)(cn=*{SEARCH_TERM}*))
    alpine.ldap.groups.search.filter=(&(objectClass=group)(objectCategory=Group)(cn=*{SEARCH_TERM}*))

    # Optional
    # Specifies the LDAP search filter used to search for users by their name.
    # The {SEARCH_TERM} variable will be substituted at runtime.
    # Example (Microsoft Active Directory):
    #    alpine.ldap.users.search.filter=(&(objectClass=group)(objectCategory=Group)(cn=*{SEARCH_TERM}*))
    # Example (ApacheDS, Fedora 389 Directory, NetIQ/Novell eDirectory, etc):
    #    alpine.ldap.users.search.filter=(&(objectClass=inetOrgPerson)(cn=*{SEARCH_TERM}*))
    alpine.ldap.users.search.filter=(&(objectClass=user)(objectCategory=Person)(cn=*{SEARCH_TERM}*))

    # Optional
    # Specifies if mapped LDAP accounts are automatically created upon successful
    # authentication. When a user logs in with valid credentials but an account has
    # not been previously provisioned, an authentication failure will be returned.
    # This allows admins to control specifically which ldap users can access the
    # system and which users cannot. When this value is set to true, a local ldap
    # user will be created and mapped to the ldap account automatically. This
    # automatic provisioning only affects authentication, not authorization.
    alpine.ldap.user.provisioning=false

    # Optional
    # This option will ensure that team memberships for LDAP users are dynamic and
    # synchronized with membership of LDAP groups. When a team is mapped to an LDAP
    # group, all local LDAP users will automatically be assigned to the team if
    # they are a member of the group the team is mapped to. If the user is later
    # removed from the LDAP group, they will also be removed from the team. This
    # option provides the ability to dynamically control user permissions via an
    # external directory.
    alpine.ldap.team.synchronization=false

    # Optional
    # HTTP proxy. If the address is set, then the port must be set too.
    # alpine.http.proxy.address=
    # alpine.http.proxy.port=
    # alpine.http.proxy.username=
    # alpine.http.proxy.password=
    # alpine.no.proxy=

    # Optional
    # Cross-Origin Resource Sharing (CORS) headers to include in REST responses.
    # If 'alpine.cors.enabled' is true, CORS headers will be sent, if false, no
    # CORS headers will be sent.
    # See Also: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
    # The following are default values
    #alpine.cors.enabled=true
    #alpine.cors.allow.origin=*
    #alpine.cors.allow.methods=GET POST PUT DELETE OPTIONS
    #alpine.cors.allow.headers=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
    #alpine.cors.expose.headers=Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
    #alpine.cors.allow.credentials=true
    #alpine.cors.max.age=3600

postgresql:
  enabled: false
```
