### ISSUE TITLE
[dependency-track] Configmap not used

### ISSUE THREAD

**Issue by wathy** [evryfs/helm-charts#7]
**Describe the bug**
When i edit the configmap, nothing happens (e.g. adding ldap configuration). The configmap also contains h2 DB config although dependency-track uses postgresql DB.

**Version of Helm and Kubernetes**:
Helm version :
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"169db3bff4b5fb7722e967c5b6356713f05f15ed", GitTreeState:"clean", BuildDate:"2020-04-03T16:14:09Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Which chart**:
Dependency-track

**What happened**:
No changes are taking into account when modifying the configmap

**What you expected to happen**:
Changes are taking into account when modifying the configmap

**How to reproduce it** (as minimally and precisely as possible):
Install the chart, change something in the configmap.

**Anything else we need to know**:
The applications.properties file is correctly updated in the config folder, but the content is not used i think

**Comment by davidkarlsen** [comment]
I believe it is in use which you can see from the following output - however keep in mind that some configuration is set via env vars too.

```
k exec -ti dependency-track-7f8cb64684-cxlnl -- sh -c set|grep -i config
ALPINE_APPLICATION_PROPERTIES='/config/application.properties'
```

```
k get deployment dependency-track -o yaml|grep -2i conf
          value: /extlib/postgresql-42.2.5.jar
        - name: ALPINE_APPLICATION_PROPERTIES
          value: /config/application.properties
        - name: ALPINE_LDAP_GROUPS_SEARCH_FILTER
          value: (&(objectClass=group)(objectCategory=Group)(cn=*{SEARCH_TERM}*))
--
--
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config
        - mountPath: /tmp
          name: tmp
--
--
        value: dts
      volumes:
      - configMap:
          defaultMode: 420
          name: dependency-track
--
--
          defaultMode: 420
          name: dependency-track
        name: config
      - emptyDir: {}
```
