### ISSUE TITLE
Help with PaaS database

### ISSUE THREAD

**Issue by marcocristofolini** [evryfs/helm-charts#78]
I need to deploy this Helm chart  but I need to use a PaaS database (azure postgresql) , nevertheless I can't change this chart to work properly with my PaaS database. Sorry to bought you guys but I'm recently started to learn about Helm and I really appreciate if any of you could help-me.

**Comment by davidkarlsen** [comment]
Which chart? Dependency-track I assume?

**Comment by davidkarlsen** [comment]
try something like this:
```
...
apiserver:
  env:
  - name: ALPINE_DATABASE_MODE
    value: "external"
  - name: ALPINE_DATABASE_DRIVER
    value: "org.postgresql.Driver"
  - name: ALPINE_DATABASE_URL
    value: jdbc:postgresql://dts-dependency-track/postgres
  - name: ALPINE_DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres.dts-dependency-track.credentials.postgresql.acid.zalan.do
        key: password
  - name: ALPINE_DATABASE_USERNAME
    valueFrom:
      secretKeyRef:
        name: postgres.dts-dependency-track.credentials.postgresql.acid.zalan.do
        key: username
postgresql:
  enabled: false
```
