### ISSUE TITLE
[ stable/dependency-track/] - Postgresql uses Hardcoded password instead of randomly generated 

### ISSUE THREAD

**Issue by Homopatrol** [evryfs/helm-charts#89]
**Describe the bug**
The Postgresql password is being hard coded in [values.yaml](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L163), it is not good practice to hardcode default credentials in Helm charts especially when the Postgresql chart contains a random-generate function to create passwords. 
```
postgresql:
  enabled: true
  postgresqlUsername: deptrack
  postgresqlPassword: deptrack
  postgresqlDatabase: deptrack
```
 this is not good practice to use a fixed password, especially when the rando-generate function is already in the chart
**Version of Helm and Kubernetes**

Helm v3.5.2
Kubernetes 1.19.0

**Which chart**:
Dependency Track 4.2.0 / Chart 1.0.4
